- id: doi:10.1016/j.envres.2023.117343
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0013935123021473-ga1.jpg
- id: doi:10.3390/ijerph20043473
  image: https://www.mdpi.com/ijerph/ijerph-20-03473/article_deploy/html/images/ijerph-20-03473-g003-550.jpg
- id: doi:10.1016/j.envres.2022.114074
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0013935122014013-gr1.jpg
- id: doi:10.3390/ijerph192013471
  image: https://www.mdpi.com/ijerph/ijerph-19-13471/article_deploy/html/images/ijerph-19-13471-g001-550.jpg
- id: doi:10.1016/j.neuro.2022.09.010
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0161813X22001553-gr1.jpg
- id: doi:10.3390/ijerph18041598
  image: https://www.mdpi.com/ijerph/ijerph-18-01598/article_deploy/html/images/ijerph-18-01598-g001-550.jpg
- id: doi:10.3390/ijerph19137886
  image: https://www.mdpi.com/ijerph/ijerph-19-07886/article_deploy/html/images/ijerph-19-07886-g006-550.jpg
- id: doi:10.1016/j.envres.2022.112722
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0013935122000494-ga1.jpg
- id: doi:https://scholarsarchive.byu.edu/cgi/viewcontent.cgi?article=2730&context=iemssconference
  image: https://www.researchgate.net/profile/Vikas-Kumar-155/publication/267828762/figure/fig2/AS:392209095512075@1470521343776/Subset-of-the-MEM-prototype-network-showing-how-the-sub-networks-developed-for-the-three_W640.jpg
